global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'publication_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'publication-service:8080' ]
        labels:
          application: 'publication service'

  - job_name: 'notification_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'notification-service:8080' ]
        labels:
          application: 'notification service'