spring:
  cloud:
    gateway:
      routes:
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/auth/**, /users/**
        - id: publication-service
          uri: lb://publication-service
          predicates:
            - Path=/publication/**
          filters:
            - AuthFilter